Repository CMU-313/fall22-hw3-valgrind-warriors, pull requests merged in 2022-10, with the labels that each got.

#10 Add database fields and update necessary get/set functions and enumerators
  docs-core/src/main/java/com/sismics/docs/core/constant/RouteStepPriorityType.java
  docs-core/src/main/java/com/sismics/docs/core/constant/RouteStepStatusType.java
  docs-core/src/main/java/com/sismics/docs/core/dao/RouteStepDao.java
  docs-core/src/main/java/com/sismics/docs/core/dao/dto/DocumentDto.java
  docs-core/src/main/java/com/sismics/docs/core/model/jpa/Document.java
  docs-core/src/main/java/com/sismics/docs/core/model/jpa/RouteStep.java
  docs-core/src/main/resources/db/update/dbupdate-000-0.sql
  docs-core/src/main/resources/db/update/dbupdate-015-0.sql
Labels: backend

#6 Middle end add proiority and status
  docs-web/src/main/java/com/sismics/docs/rest/resource/RouteModelResource.java
  docs-web/src/main/java/com/sismics/docs/rest/resource/RouteResource.java
Labels: middleware

#13 Fix drop down help
  docs-web/src/main/java/com/sismics/docs/rest/resource/RouteResource.java
  docs-web/src/main/webapp/src/app/docs/controller/settings/SettingsWorkflowEdit.js
  docs-web/src/main/webapp/src/locale/en.json
  docs-web/src/main/webapp/src/partial/docs/settings.workflow.edit.html
Labels: frontend

#16 Improve teedy task management board feature
  README.md
  docs-core/src/main/java/com/sismics/docs/core/constant/RouteStepPriorityType.java
  docs-core/src/main/java/com/sismics/docs/core/constant/RouteStepStatusType.java
  docs-core/src/main/java/com/sismics/docs/core/dao/RouteStepDao.java
  docs-core/src/main/java/com/sismics/docs/core/dao/dto/DocumentDto.java
  docs-core/src/main/java/com/sismics/docs/core/dao/dto/RouteStepDto.java
  docs-core/src/main/java/com/sismics/docs/core/model/jpa/Document.java
  docs-core/src/main/java/com/sismics/docs/core/model/jpa/RouteStep.java
  docs-core/src/main/resources/config.properties
  docs-core/src/main/resources/db/update/dbupdate-000-0.sql
  docs-core/src/main/resources/db/update/dbupdate-015-0.sql
  docs-core/src/main/resources/db/update/dbupdate-028-0.sql
  docs-web/src/dev/resources/config.properties
  docs-web/src/main/java/com/sismics/docs/rest/resource/RouteModelResource.java
  docs-web/src/main/java/com/sismics/docs/rest/resource/RouteResource.java
  docs-web/src/main/webapp/src/app/docs/controller/settings/SettingsWorkflowEdit.js
  docs-web/src/main/webapp/src/locale/en.json
  docs-web/src/main/webapp/src/partial/docs/document.default.html
  docs-web/src/main/webapp/src/partial/docs/document.view.workflow.html
  docs-web/src/main/webapp/src/partial/docs/settings.workflow.edit.html
  docs-web/src/main/webapp/src/style/bootstrap.css
  docs-web/src/prod/resources/config.properties
  docs-web/src/test/java/com/sismics/docs/rest/TestRouteResource.java
Labels: frontend, middleware, backend, testing, Dashboard
